#!/bin/bash

# Build Soring Boot application on Ubuntu 20.04
sudo apt update

# Install OpenJDK
sudo apt install -y openjdk-22-jdk

# Install Maven
sudo apt install -y maven

# Installer Node.js et npm
sudo apt install nodejs
sudo apt install npm

# Installer Angular CLI
sudo npm install -g @angular/cli

# Navigate to the frontend directory
cd frontend

# Install the frontend application
npm i

# Launch the frontend application
ng serve --proxy-config proxy.conf.json

# Navigate to the backend directory
cd ..

# Start the Spring Boot application already compiled(assuming it's a WAR file)
java -jar ClubHubFinal-0.0.1-SNAPSHOT.war

# End of file
